### ISSUE TITLE
Frontend Application , not displaying the random numbers for multiplication

### ISSUE THREAD

**Issue by varmabjr** [microservices-practical/microservices-v8#2]
Hi , I am going through your book and was able to execute the front end code until microservices-v7 , but in the v8 , i am able to make all the changes register the services on eureka but the front end does not show up the multiplication random numbers
not sure what mistake i have done , unable to diagnose can you please help.

![Capture](https://user-images.githubusercontent.com/6270889/99041545-22e7fc80-25b1-11eb-927a-c3c3953ffca6.JPG)

Thanks for the wonderful book !!

**Comment by varmabjr** [comment]
I am able to resolve it -- problem with CORS 
i had to add the below line in the configuration files 
"registry.addMapping("/api/**")
        .allowedOrigins("http://localhost:9090");"

**Comment by mechero** [comment]
Hi @varmabjr, I'm glad you solved it! Feel free to post any further question/issue you may find in your journey!
